"""vbwd_all_tables

Revision ID: vbwd_001
Revises: 
Create Date: 2026-04-02 17:19:20.721559+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'vbwd_001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arcana',
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('suit', sa.String(length=50), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('arcana_type', sa.String(length=50), nullable=False),
    sa.Column('upright_meaning', sa.Text(), nullable=False),
    sa.Column('reversed_meaning', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arcana_arcana_type'), 'arcana', ['arcana_type'], unique=False)
    op.create_index(op.f('ix_arcana_name'), 'arcana', ['name'], unique=False)
    op.create_index(op.f('ix_arcana_number'), 'arcana', ['number'], unique=False)
    op.create_index(op.f('ix_arcana_rank'), 'arcana', ['rank'], unique=False)
    op.create_index(op.f('ix_arcana_suit'), 'arcana', ['suit'], unique=False)
    op.create_table('booking_custom_schema',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_custom_schema_slug'), 'booking_custom_schema', ['slug'], unique=True)
    op.create_table('booking_export_rule',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('cron_export_scope', sa.String(length=50), nullable=True),
    sa.Column('cron_entity', sa.String(length=50), nullable=True),
    sa.Column('cron_status_filter', sa.String(length=255), nullable=True),
    sa.Column('export_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_export_rule_event_type'), 'booking_export_rule', ['event_type'], unique=False)
    op.create_table('booking_resource_category',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['booking_resource_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_resource_category_slug'), 'booking_resource_category', ['slug'], unique=True)
    op.create_table('cms_category',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['cms_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_category_parent_id'), 'cms_category', ['parent_id'], unique=False)
    op.create_index(op.f('ix_cms_category_slug'), 'cms_category', ['slug'], unique=True)
    op.create_table('cms_image',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('url_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('og_image_url', sa.String(length=512), nullable=True),
    sa.Column('robots', sa.String(length=64), nullable=True),
    sa.Column('schema_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_image_slug'), 'cms_image', ['slug'], unique=True)
    op.create_table('cms_layout',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('areas', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_layout_slug'), 'cms_layout', ['slug'], unique=True)
    op.create_table('cms_routing_rules',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=32), nullable=False),
    sa.Column('match_value', sa.String(length=255), nullable=True),
    sa.Column('target_slug', sa.String(length=255), nullable=False),
    sa.Column('redirect_code', sa.Integer(), nullable=False),
    sa.Column('is_rewrite', sa.Boolean(), nullable=False),
    sa.Column('layer', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_style',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_css', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_style_slug'), 'cms_style', ['slug'], unique=True)
    op.create_table('cms_widget',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('widget_type', sa.String(length=32), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('source_css', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_widget_slug'), 'cms_widget', ['slug'], unique=True)
    op.create_table('discount',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', 'FREE_SHIPPING', 'BUY_X_GET_Y', name='discount_type_enum'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('scope', sa.Enum('GLOBAL', 'ECOMMERCE', 'SUBSCRIPTION', 'BOOKING', name='discount_scope_enum'), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_slug'), 'discount', ['slug'], unique=True)
    op.create_table('email_template',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_template_event_type'), 'email_template', ['event_type'], unique=True)
    op.create_table('shop_product',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_float', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_digital', sa.Boolean(), nullable=False),
    sa.Column('has_variants', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('product_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tax_class', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_product_is_active'), 'shop_product', ['is_active'], unique=False)
    op.create_index(op.f('ix_shop_product_sku'), 'shop_product', ['sku'], unique=True)
    op.create_index(op.f('ix_shop_product_slug'), 'shop_product', ['slug'], unique=True)
    op.create_table('shop_product_category',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['shop_product_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_product_category_parent_id'), 'shop_product_category', ['parent_id'], unique=False)
    op.create_index(op.f('ix_shop_product_category_slug'), 'shop_product_category', ['slug'], unique=True)
    op.create_table('shop_warehouse',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_warehouse_slug'), 'shop_warehouse', ['slug'], unique=True)
    op.create_table('taro_session',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('spread_id', sa.String(length=50), nullable=False),
    sa.Column('tokens_consumed', sa.Integer(), nullable=False),
    sa.Column('follow_up_count', sa.Integer(), nullable=False),
    sa.Column('max_follow_ups', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taro_session_expires_at'), 'taro_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_taro_session_spread_id'), 'taro_session', ['spread_id'], unique=False)
    op.create_index(op.f('ix_taro_session_status'), 'taro_session', ['status'], unique=False)
    op.create_index(op.f('ix_taro_session_user_id'), 'taro_session', ['user_id'], unique=False)
    op.create_table('vbwd_addon',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_period', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_addon_is_active'), 'vbwd_addon', ['is_active'], unique=False)
    op.create_index(op.f('ix_vbwd_addon_slug'), 'vbwd_addon', ['slug'], unique=True)
    op.create_table('vbwd_country',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_country_code'), 'vbwd_country', ['code'], unique=True)
    op.create_index(op.f('ix_vbwd_country_is_enabled'), 'vbwd_country', ['is_enabled'], unique=False)
    op.create_table('vbwd_currency',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_currency_code'), 'vbwd_currency', ['code'], unique=True)
    op.create_table('vbwd_payment_method',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('plugin_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currencies', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('countries', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fee_charged_to', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_payment_method_code'), 'vbwd_payment_method', ['code'], unique=True)
    op.create_index(op.f('ix_vbwd_payment_method_is_active'), 'vbwd_payment_method', ['is_active'], unique=False)
    op.create_table('vbwd_permission',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_permission_name'), 'vbwd_permission', ['name'], unique=True)
    op.create_index(op.f('ix_vbwd_permission_resource'), 'vbwd_permission', ['resource'], unique=False)
    op.create_table('vbwd_role',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_role_name'), 'vbwd_role', ['name'], unique=True)
    op.create_table('vbwd_tarif_plan_category',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_single', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['vbwd_tarif_plan_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_tarif_plan_category_parent_id'), 'vbwd_tarif_plan_category', ['parent_id'], unique=False)
    op.create_index(op.f('ix_vbwd_tarif_plan_category_slug'), 'vbwd_tarif_plan_category', ['slug'], unique=True)
    op.create_table('vbwd_tax',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_inclusive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_tax_code'), 'vbwd_tax', ['code'], unique=True)
    op.create_index(op.f('ix_vbwd_tax_country_code'), 'vbwd_tax', ['country_code'], unique=False)
    op.create_table('vbwd_token_bundle',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('token_amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_token_bundle_is_active'), 'vbwd_token_bundle', ['is_active'], unique=False)
    op.create_table('vbwd_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus'), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'VENDOR', name='userrole'), nullable=False),
    sa.Column('payment_customer_id', sa.String(length=255), nullable=True),
    sa.Column('has_used_trial', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_user_email'), 'vbwd_user', ['email'], unique=True)
    op.create_index(op.f('ix_vbwd_user_payment_customer_id'), 'vbwd_user', ['payment_customer_id'], unique=True)
    op.create_index(op.f('ix_vbwd_user_status'), 'vbwd_user', ['status'], unique=False)
    op.create_table('booking_resource',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_schema_id', sa.UUID(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('price_unit', sa.String(length=50), nullable=True),
    sa.Column('availability', sa.JSON(), nullable=False),
    sa.Column('custom_fields_schema', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_schema_id'], ['booking_custom_schema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_resource_slug'), 'booking_resource', ['slug'], unique=True)
    op.create_table('cms_layout_widget',
    sa.Column('layout_id', sa.UUID(), nullable=False),
    sa.Column('widget_id', sa.UUID(), nullable=False),
    sa.Column('area_name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['cms_layout.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['cms_widget.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_layout_widget_layout_id'), 'cms_layout_widget', ['layout_id'], unique=False)
    op.create_index(op.f('ix_cms_layout_widget_widget_id'), 'cms_layout_widget', ['widget_id'], unique=False)
    op.create_table('cms_menu_item',
    sa.Column('widget_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('page_slug', sa.String(length=512), nullable=True),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['cms_menu_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['cms_widget.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_menu_item_parent_id'), 'cms_menu_item', ['parent_id'], unique=False)
    op.create_index(op.f('ix_cms_menu_item_widget_id'), 'cms_menu_item', ['widget_id'], unique=False)
    op.create_table('cms_page',
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('source_css', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.Text(), nullable=True),
    sa.Column('og_title', sa.String(length=255), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('og_image_url', sa.String(length=512), nullable=True),
    sa.Column('canonical_url', sa.String(length=512), nullable=True),
    sa.Column('robots', sa.String(length=64), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=True),
    sa.Column('layout_id', sa.UUID(), nullable=True),
    sa.Column('style_id', sa.UUID(), nullable=True),
    sa.Column('use_theme_switcher_styles', sa.Boolean(), nullable=False),
    sa.Column('preview_token', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['cms_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['layout_id'], ['cms_layout.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['style_id'], ['cms_style.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_page_category_id'), 'cms_page', ['category_id'], unique=False)
    op.create_index(op.f('ix_cms_page_layout_id'), 'cms_page', ['layout_id'], unique=False)
    op.create_index(op.f('ix_cms_page_preview_token'), 'cms_page', ['preview_token'], unique=False)
    op.create_index(op.f('ix_cms_page_slug'), 'cms_page', ['slug'], unique=True)
    op.create_index(op.f('ix_cms_page_style_id'), 'cms_page', ['style_id'], unique=False)
    op.create_table('coupon',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_id', sa.UUID(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_code'), 'coupon', ['code'], unique=True)
    op.create_index(op.f('ix_coupon_discount_id'), 'coupon', ['discount_id'], unique=False)
    op.create_table('ghrm_user_github_access',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('github_username', sa.String(length=128), nullable=False),
    sa.Column('github_user_id', sa.String(length=32), nullable=False),
    sa.Column('oauth_token', sa.Text(), nullable=True),
    sa.Column('oauth_scope', sa.String(length=256), nullable=True),
    sa.Column('deploy_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('access_status', sa.String(length=32), nullable=False),
    sa.Column('grace_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ghrm_user_github_access_user_id'), 'ghrm_user_github_access', ['user_id'], unique=True)
    op.create_table('shop_abandoned_cart',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('cart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cart_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'REMINDER_1_SENT', 'REMINDER_2_SENT', 'REMINDER_3_SENT', 'RECOVERED', 'EXPIRED', name='shop_abandonedcartstatus'), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('reminder_1_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_2_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_3_at', sa.DateTime(), nullable=True),
    sa.Column('recovered_at', sa.DateTime(), nullable=True),
    sa.Column('recovery_invoice_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_abandoned_cart_invoice_id'), 'shop_abandoned_cart', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_shop_abandoned_cart_status'), 'shop_abandoned_cart', ['status'], unique=False)
    op.create_index(op.f('ix_shop_abandoned_cart_user_id'), 'shop_abandoned_cart', ['user_id'], unique=False)
    op.create_table('shop_product_category_link',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['shop_product_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'product_id')
    )
    op.create_table('shop_product_image',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_product_image_product_id'), 'shop_product_image', ['product_id'], unique=False)
    op.create_table('shop_product_review',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='shop_reviewstatus'), nullable=False),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_product_review_product_id'), 'shop_product_review', ['product_id'], unique=False)
    op.create_index(op.f('ix_shop_product_review_status'), 'shop_product_review', ['status'], unique=False)
    op.create_index(op.f('ix_shop_product_review_user_id'), 'shop_product_review', ['user_id'], unique=False)
    op.create_table('shop_product_variant',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_float', sa.Float(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_product_variant_product_id'), 'shop_product_variant', ['product_id'], unique=False)
    op.create_index(op.f('ix_shop_product_variant_sku'), 'shop_product_variant', ['sku'], unique=True)
    op.create_table('taro_card_draw',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('arcana_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('orientation', sa.String(length=50), nullable=False),
    sa.Column('ai_interpretation', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arcana_id'], ['arcana.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taro_card_draw_arcana_id'), 'taro_card_draw', ['arcana_id'], unique=False)
    op.create_index(op.f('ix_taro_card_draw_position'), 'taro_card_draw', ['position'], unique=False)
    op.create_index(op.f('ix_taro_card_draw_session_id'), 'taro_card_draw', ['session_id'], unique=False)
    op.create_table('vbwd_feature_usage',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feature_name', 'period_start', name='uq_user_feature_period')
    )
    op.create_index(op.f('ix_vbwd_feature_usage_feature_name'), 'vbwd_feature_usage', ['feature_name'], unique=False)
    op.create_index(op.f('ix_vbwd_feature_usage_period_start'), 'vbwd_feature_usage', ['period_start'], unique=False)
    op.create_index(op.f('ix_vbwd_feature_usage_user_id'), 'vbwd_feature_usage', ['user_id'], unique=False)
    op.create_table('vbwd_password_reset_token',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_password_reset_token_token'), 'vbwd_password_reset_token', ['token'], unique=True)
    op.create_index(op.f('ix_vbwd_password_reset_token_user_id'), 'vbwd_password_reset_token', ['user_id'], unique=False)
    op.create_table('vbwd_payment_method_translation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('payment_method_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['vbwd_payment_method.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_method_id', 'locale', name='uq_payment_method_translation_locale')
    )
    op.create_index(op.f('ix_vbwd_payment_method_translation_payment_method_id'), 'vbwd_payment_method_translation', ['payment_method_id'], unique=False)
    op.create_table('vbwd_price',
    sa.Column('price_float', sa.Float(), nullable=False),
    sa.Column('price_decimal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('taxes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['vbwd_currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_price_currency_id'), 'vbwd_price', ['currency_id'], unique=False)
    op.create_table('vbwd_role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['vbwd_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['vbwd_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('vbwd_tax_rate',
    sa.Column('tax_id', sa.UUID(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tax_id'], ['vbwd_tax.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_tax_rate_tax_id'), 'vbwd_tax_rate', ['tax_id'], unique=False)
    op.create_table('vbwd_token_transaction',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('PURCHASE', 'USAGE', 'REFUND', 'BONUS', 'ADJUSTMENT', 'SUBSCRIPTION', name='tokentransactiontype'), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_token_transaction_reference_id'), 'vbwd_token_transaction', ['reference_id'], unique=False)
    op.create_index(op.f('ix_vbwd_token_transaction_user_id'), 'vbwd_token_transaction', ['user_id'], unique=False)
    op.create_table('vbwd_user_case',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_started', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='usercasestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_user_case_status'), 'vbwd_user_case', ['status'], unique=False)
    op.create_index(op.f('ix_vbwd_user_case_user_id'), 'vbwd_user_case', ['user_id'], unique=False)
    op.create_table('vbwd_user_details',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('tax_number', sa.String(length=100), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_user_details_user_id'), 'vbwd_user_details', ['user_id'], unique=True)
    op.create_table('vbwd_user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['vbwd_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('vbwd_user_token_balance',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_user_token_balance_user_id'), 'vbwd_user_token_balance', ['user_id'], unique=True)
    op.create_table('booking_resource_category_link',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['booking_resource_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['booking_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'category_id')
    )
    op.create_table('booking_resource_image',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('cms_image_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cms_image_id'], ['cms_image.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['booking_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'cms_image_id')
    )
    op.create_index(op.f('ix_booking_resource_image_resource_id'), 'booking_resource_image', ['resource_id'], unique=False)
    op.create_table('booking_resource_slot_block',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('blocked_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_by'], ['vbwd_user.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['booking_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_resource_slot_block_resource_id'), 'booking_resource_slot_block', ['resource_id'], unique=False)
    op.create_index('ix_slot_block_resource_date', 'booking_resource_slot_block', ['resource_id', 'date'], unique=False)
    op.create_table('cms_page_content_block',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('area_name', sa.String(length=100), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('source_css', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['cms_page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'area_name', name='uq_page_content_block_area')
    )
    op.create_index(op.f('ix_cms_page_content_block_page_id'), 'cms_page_content_block', ['page_id'], unique=False)
    op.create_table('shop_stock_block',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMMITTED', 'RELEASED', 'EXPIRED', name='shop_stockblockstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['shop_product_variant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['shop_warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_stock_block_expires_at'), 'shop_stock_block', ['expires_at'], unique=False)
    op.create_index(op.f('ix_shop_stock_block_product_id'), 'shop_stock_block', ['product_id'], unique=False)
    op.create_index(op.f('ix_shop_stock_block_session_id'), 'shop_stock_block', ['session_id'], unique=False)
    op.create_index(op.f('ix_shop_stock_block_status'), 'shop_stock_block', ['status'], unique=False)
    op.create_index(op.f('ix_shop_stock_block_variant_id'), 'shop_stock_block', ['variant_id'], unique=False)
    op.create_index(op.f('ix_shop_stock_block_warehouse_id'), 'shop_stock_block', ['warehouse_id'], unique=False)
    op.create_table('shop_warehouse_stock',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['shop_product_variant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['shop_warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', 'variant_id', name='uq_warehouse_product_variant')
    )
    op.create_index(op.f('ix_shop_warehouse_stock_product_id'), 'shop_warehouse_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_shop_warehouse_stock_variant_id'), 'shop_warehouse_stock', ['variant_id'], unique=False)
    op.create_index(op.f('ix_shop_warehouse_stock_warehouse_id'), 'shop_warehouse_stock', ['warehouse_id'], unique=False)
    op.create_table('shop_wishlist_item',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['shop_product_variant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', 'variant_id', name='uq_wishlist_user_product_variant')
    )
    op.create_index(op.f('ix_shop_wishlist_item_product_id'), 'shop_wishlist_item', ['product_id'], unique=False)
    op.create_index(op.f('ix_shop_wishlist_item_user_id'), 'shop_wishlist_item', ['user_id'], unique=False)
    op.create_table('vbwd_tarif_plan',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_float', sa.Float(), nullable=False),
    sa.Column('price_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('billing_period', sa.Enum('MONTHLY', 'YEARLY', 'QUARTERLY', 'WEEKLY', 'DAILY', 'ONE_TIME', name='billingperiod'), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['vbwd_price.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_tarif_plan_is_active'), 'vbwd_tarif_plan', ['is_active'], unique=False)
    op.create_index(op.f('ix_vbwd_tarif_plan_price_id'), 'vbwd_tarif_plan', ['price_id'], unique=False)
    op.create_index(op.f('ix_vbwd_tarif_plan_slug'), 'vbwd_tarif_plan', ['slug'], unique=True)
    op.create_table('ghrm_software_package',
    sa.Column('tariff_plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('github_owner', sa.String(length=128), nullable=False),
    sa.Column('github_repo', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('github_protected_branch', sa.String(length=64), nullable=False),
    sa.Column('github_installation_id', sa.String(length=64), nullable=True),
    sa.Column('sync_api_key', sa.String(length=128), nullable=False),
    sa.Column('tech_specs', sa.JSON(), nullable=True),
    sa.Column('related_slugs', sa.JSON(), nullable=True),
    sa.Column('download_counter', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tariff_plan_id'], ['vbwd_tarif_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_owner', 'github_repo', name='uq_ghrm_pkg_owner_repo')
    )
    op.create_index(op.f('ix_ghrm_software_package_slug'), 'ghrm_software_package', ['slug'], unique=True)
    op.create_index(op.f('ix_ghrm_software_package_tariff_plan_id'), 'ghrm_software_package', ['tariff_plan_id'], unique=True)
    op.create_table('vbwd_addon_tarif_plans',
    sa.Column('addon_id', sa.UUID(), nullable=False),
    sa.Column('tarif_plan_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['vbwd_addon.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarif_plan_id'], ['vbwd_tarif_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('addon_id', 'tarif_plan_id')
    )
    op.create_table('vbwd_subscription',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tarif_plan_id', sa.UUID(), nullable=False),
    sa.Column('pending_plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'TRIALING', 'PAUSED', 'CANCELLED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('trial_end_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('payment_failed_at', sa.DateTime(), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pending_plan_id'], ['vbwd_tarif_plan.id'], ),
    sa.ForeignKeyConstraint(['tarif_plan_id'], ['vbwd_tarif_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_subscription_expires_at'), 'vbwd_subscription', ['expires_at'], unique=False)
    op.create_index(op.f('ix_vbwd_subscription_provider_subscription_id'), 'vbwd_subscription', ['provider_subscription_id'], unique=True)
    op.create_index(op.f('ix_vbwd_subscription_status'), 'vbwd_subscription', ['status'], unique=False)
    op.create_index(op.f('ix_vbwd_subscription_user_id'), 'vbwd_subscription', ['user_id'], unique=False)
    op.create_table('vbwd_tarif_plan_category_plans',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('tarif_plan_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['vbwd_tarif_plan_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarif_plan_id'], ['vbwd_tarif_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'tarif_plan_id')
    )
    op.create_table('ghrm_access_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['ghrm_software_package.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ghrm_access_log_package_id'), 'ghrm_access_log', ['package_id'], unique=False)
    op.create_index(op.f('ix_ghrm_access_log_user_id'), 'ghrm_access_log', ['user_id'], unique=False)
    op.create_table('ghrm_software_sync',
    sa.Column('software_package_id', sa.UUID(), nullable=False),
    sa.Column('latest_version', sa.String(length=64), nullable=True),
    sa.Column('latest_released_at', sa.DateTime(), nullable=True),
    sa.Column('cached_readme', sa.Text(), nullable=True),
    sa.Column('cached_changelog', sa.Text(), nullable=True),
    sa.Column('cached_docs', sa.Text(), nullable=True),
    sa.Column('cached_releases', sa.JSON(), nullable=True),
    sa.Column('cached_screenshots', sa.JSON(), nullable=True),
    sa.Column('override_readme', sa.Text(), nullable=True),
    sa.Column('override_changelog', sa.Text(), nullable=True),
    sa.Column('override_docs', sa.Text(), nullable=True),
    sa.Column('admin_screenshots', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['software_package_id'], ['ghrm_software_package.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ghrm_software_sync_software_package_id'), 'ghrm_software_sync', ['software_package_id'], unique=True)
    op.create_table('vbwd_user_invoice',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tarif_plan_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHORIZED', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED', name='invoicestatus'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_ref', sa.String(length=255), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('invoiced_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('provider_session_id', sa.String(length=255), nullable=True),
    sa.Column('payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['vbwd_subscription.id'], ),
    sa.ForeignKeyConstraint(['tarif_plan_id'], ['vbwd_tarif_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_user_invoice_invoice_number'), 'vbwd_user_invoice', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_vbwd_user_invoice_payment_intent_id'), 'vbwd_user_invoice', ['payment_intent_id'], unique=False)
    op.create_index(op.f('ix_vbwd_user_invoice_provider_session_id'), 'vbwd_user_invoice', ['provider_session_id'], unique=True)
    op.create_index(op.f('ix_vbwd_user_invoice_status'), 'vbwd_user_invoice', ['status'], unique=False)
    op.create_index(op.f('ix_vbwd_user_invoice_user_id'), 'vbwd_user_invoice', ['user_id'], unique=False)
    op.create_table('booking',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['vbwd_user_invoice.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['booking_resource.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_invoice_id'), 'booking', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_booking_resource_id'), 'booking', ['resource_id'], unique=False)
    op.create_index(op.f('ix_booking_start_at'), 'booking', ['start_at'], unique=False)
    op.create_index(op.f('ix_booking_user_id'), 'booking', ['user_id'], unique=False)
    op.create_table('coupon_usage',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['vbwd_user_invoice.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_usage_coupon_id'), 'coupon_usage', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_usage_invoice_id'), 'coupon_usage', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_coupon_usage_user_id'), 'coupon_usage', ['user_id'], unique=False)
    op.create_table('shop_order',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='shop_orderstatus'), nullable=False),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shipping_method', sa.String(length=100), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('tracking_url', sa.String(length=500), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['vbwd_user_invoice.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_order_invoice_id'), 'shop_order', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_shop_order_order_number'), 'shop_order', ['order_number'], unique=True)
    op.create_index(op.f('ix_shop_order_status'), 'shop_order', ['status'], unique=False)
    op.create_index(op.f('ix_shop_order_user_id'), 'shop_order', ['user_id'], unique=False)
    op.create_table('vbwd_addon_subscription',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('addon_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'TRIALING', 'PAUSED', 'CANCELLED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['vbwd_addon.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['vbwd_user_invoice.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['vbwd_subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_addon_subscription_addon_id'), 'vbwd_addon_subscription', ['addon_id'], unique=False)
    op.create_index(op.f('ix_vbwd_addon_subscription_expires_at'), 'vbwd_addon_subscription', ['expires_at'], unique=False)
    op.create_index(op.f('ix_vbwd_addon_subscription_invoice_id'), 'vbwd_addon_subscription', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_vbwd_addon_subscription_provider_subscription_id'), 'vbwd_addon_subscription', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_vbwd_addon_subscription_status'), 'vbwd_addon_subscription', ['status'], unique=False)
    op.create_index(op.f('ix_vbwd_addon_subscription_subscription_id'), 'vbwd_addon_subscription', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_vbwd_addon_subscription_user_id'), 'vbwd_addon_subscription', ['user_id'], unique=False)
    op.create_table('vbwd_invoice_line_item',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('SUBSCRIPTION', 'TOKEN_BUNDLE', 'ADD_ON', 'CUSTOM', name='lineitemtype'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['vbwd_user_invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_invoice_line_item_invoice_id'), 'vbwd_invoice_line_item', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_vbwd_invoice_line_item_item_id'), 'vbwd_invoice_line_item', ['item_id'], unique=False)
    op.create_table('vbwd_token_bundle_purchase',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'REFUNDED', 'CANCELLED', name='purchasestatus'), nullable=False),
    sa.Column('tokens_credited', sa.Boolean(), nullable=False),
    sa.Column('token_amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['vbwd_token_bundle.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['vbwd_user_invoice.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vbwd_token_bundle_purchase_bundle_id'), 'vbwd_token_bundle_purchase', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_vbwd_token_bundle_purchase_invoice_id'), 'vbwd_token_bundle_purchase', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_vbwd_token_bundle_purchase_status'), 'vbwd_token_bundle_purchase', ['status'], unique=False)
    op.create_index(op.f('ix_vbwd_token_bundle_purchase_user_id'), 'vbwd_token_bundle_purchase', ['user_id'], unique=False)
    op.create_table('discount_application',
    sa.Column('discount_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('line_item_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['vbwd_user_invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_item_id'], ['vbwd_invoice_line_item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['vbwd_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_application_discount_id'), 'discount_application', ['discount_id'], unique=False)
    op.create_index(op.f('ix_discount_application_invoice_id'), 'discount_application', ['invoice_id'], unique=False)
    op.create_table('shop_order_item',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_refunded', sa.Boolean(), nullable=False),
    sa.Column('refunded_quantity', sa.Integer(), nullable=False),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shop_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['shop_product_variant.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['shop_warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_order_item_order_id'), 'shop_order_item', ['order_id'], unique=False)
    op.create_index(op.f('ix_shop_order_item_product_id'), 'shop_order_item', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_order_item_product_id'), table_name='shop_order_item')
    op.drop_index(op.f('ix_shop_order_item_order_id'), table_name='shop_order_item')
    op.drop_table('shop_order_item')
    op.drop_index(op.f('ix_discount_application_invoice_id'), table_name='discount_application')
    op.drop_index(op.f('ix_discount_application_discount_id'), table_name='discount_application')
    op.drop_table('discount_application')
    op.drop_index(op.f('ix_vbwd_token_bundle_purchase_user_id'), table_name='vbwd_token_bundle_purchase')
    op.drop_index(op.f('ix_vbwd_token_bundle_purchase_status'), table_name='vbwd_token_bundle_purchase')
    op.drop_index(op.f('ix_vbwd_token_bundle_purchase_invoice_id'), table_name='vbwd_token_bundle_purchase')
    op.drop_index(op.f('ix_vbwd_token_bundle_purchase_bundle_id'), table_name='vbwd_token_bundle_purchase')
    op.drop_table('vbwd_token_bundle_purchase')
    op.drop_index(op.f('ix_vbwd_invoice_line_item_item_id'), table_name='vbwd_invoice_line_item')
    op.drop_index(op.f('ix_vbwd_invoice_line_item_invoice_id'), table_name='vbwd_invoice_line_item')
    op.drop_table('vbwd_invoice_line_item')
    op.drop_index(op.f('ix_vbwd_addon_subscription_user_id'), table_name='vbwd_addon_subscription')
    op.drop_index(op.f('ix_vbwd_addon_subscription_subscription_id'), table_name='vbwd_addon_subscription')
    op.drop_index(op.f('ix_vbwd_addon_subscription_status'), table_name='vbwd_addon_subscription')
    op.drop_index(op.f('ix_vbwd_addon_subscription_provider_subscription_id'), table_name='vbwd_addon_subscription')
    op.drop_index(op.f('ix_vbwd_addon_subscription_invoice_id'), table_name='vbwd_addon_subscription')
    op.drop_index(op.f('ix_vbwd_addon_subscription_expires_at'), table_name='vbwd_addon_subscription')
    op.drop_index(op.f('ix_vbwd_addon_subscription_addon_id'), table_name='vbwd_addon_subscription')
    op.drop_table('vbwd_addon_subscription')
    op.drop_index(op.f('ix_shop_order_user_id'), table_name='shop_order')
    op.drop_index(op.f('ix_shop_order_status'), table_name='shop_order')
    op.drop_index(op.f('ix_shop_order_order_number'), table_name='shop_order')
    op.drop_index(op.f('ix_shop_order_invoice_id'), table_name='shop_order')
    op.drop_table('shop_order')
    op.drop_index(op.f('ix_coupon_usage_user_id'), table_name='coupon_usage')
    op.drop_index(op.f('ix_coupon_usage_invoice_id'), table_name='coupon_usage')
    op.drop_index(op.f('ix_coupon_usage_coupon_id'), table_name='coupon_usage')
    op.drop_table('coupon_usage')
    op.drop_index(op.f('ix_booking_user_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_start_at'), table_name='booking')
    op.drop_index(op.f('ix_booking_resource_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_invoice_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_vbwd_user_invoice_user_id'), table_name='vbwd_user_invoice')
    op.drop_index(op.f('ix_vbwd_user_invoice_status'), table_name='vbwd_user_invoice')
    op.drop_index(op.f('ix_vbwd_user_invoice_provider_session_id'), table_name='vbwd_user_invoice')
    op.drop_index(op.f('ix_vbwd_user_invoice_payment_intent_id'), table_name='vbwd_user_invoice')
    op.drop_index(op.f('ix_vbwd_user_invoice_invoice_number'), table_name='vbwd_user_invoice')
    op.drop_table('vbwd_user_invoice')
    op.drop_index(op.f('ix_ghrm_software_sync_software_package_id'), table_name='ghrm_software_sync')
    op.drop_table('ghrm_software_sync')
    op.drop_index(op.f('ix_ghrm_access_log_user_id'), table_name='ghrm_access_log')
    op.drop_index(op.f('ix_ghrm_access_log_package_id'), table_name='ghrm_access_log')
    op.drop_table('ghrm_access_log')
    op.drop_table('vbwd_tarif_plan_category_plans')
    op.drop_index(op.f('ix_vbwd_subscription_user_id'), table_name='vbwd_subscription')
    op.drop_index(op.f('ix_vbwd_subscription_status'), table_name='vbwd_subscription')
    op.drop_index(op.f('ix_vbwd_subscription_provider_subscription_id'), table_name='vbwd_subscription')
    op.drop_index(op.f('ix_vbwd_subscription_expires_at'), table_name='vbwd_subscription')
    op.drop_table('vbwd_subscription')
    op.drop_table('vbwd_addon_tarif_plans')
    op.drop_index(op.f('ix_ghrm_software_package_tariff_plan_id'), table_name='ghrm_software_package')
    op.drop_index(op.f('ix_ghrm_software_package_slug'), table_name='ghrm_software_package')
    op.drop_table('ghrm_software_package')
    op.drop_index(op.f('ix_vbwd_tarif_plan_slug'), table_name='vbwd_tarif_plan')
    op.drop_index(op.f('ix_vbwd_tarif_plan_price_id'), table_name='vbwd_tarif_plan')
    op.drop_index(op.f('ix_vbwd_tarif_plan_is_active'), table_name='vbwd_tarif_plan')
    op.drop_table('vbwd_tarif_plan')
    op.drop_index(op.f('ix_shop_wishlist_item_user_id'), table_name='shop_wishlist_item')
    op.drop_index(op.f('ix_shop_wishlist_item_product_id'), table_name='shop_wishlist_item')
    op.drop_table('shop_wishlist_item')
    op.drop_index(op.f('ix_shop_warehouse_stock_warehouse_id'), table_name='shop_warehouse_stock')
    op.drop_index(op.f('ix_shop_warehouse_stock_variant_id'), table_name='shop_warehouse_stock')
    op.drop_index(op.f('ix_shop_warehouse_stock_product_id'), table_name='shop_warehouse_stock')
    op.drop_table('shop_warehouse_stock')
    op.drop_index(op.f('ix_shop_stock_block_warehouse_id'), table_name='shop_stock_block')
    op.drop_index(op.f('ix_shop_stock_block_variant_id'), table_name='shop_stock_block')
    op.drop_index(op.f('ix_shop_stock_block_status'), table_name='shop_stock_block')
    op.drop_index(op.f('ix_shop_stock_block_session_id'), table_name='shop_stock_block')
    op.drop_index(op.f('ix_shop_stock_block_product_id'), table_name='shop_stock_block')
    op.drop_index(op.f('ix_shop_stock_block_expires_at'), table_name='shop_stock_block')
    op.drop_table('shop_stock_block')
    op.drop_index(op.f('ix_cms_page_content_block_page_id'), table_name='cms_page_content_block')
    op.drop_table('cms_page_content_block')
    op.drop_index('ix_slot_block_resource_date', table_name='booking_resource_slot_block')
    op.drop_index(op.f('ix_booking_resource_slot_block_resource_id'), table_name='booking_resource_slot_block')
    op.drop_table('booking_resource_slot_block')
    op.drop_index(op.f('ix_booking_resource_image_resource_id'), table_name='booking_resource_image')
    op.drop_table('booking_resource_image')
    op.drop_table('booking_resource_category_link')
    op.drop_index(op.f('ix_vbwd_user_token_balance_user_id'), table_name='vbwd_user_token_balance')
    op.drop_table('vbwd_user_token_balance')
    op.drop_table('vbwd_user_roles')
    op.drop_index(op.f('ix_vbwd_user_details_user_id'), table_name='vbwd_user_details')
    op.drop_table('vbwd_user_details')
    op.drop_index(op.f('ix_vbwd_user_case_user_id'), table_name='vbwd_user_case')
    op.drop_index(op.f('ix_vbwd_user_case_status'), table_name='vbwd_user_case')
    op.drop_table('vbwd_user_case')
    op.drop_index(op.f('ix_vbwd_token_transaction_user_id'), table_name='vbwd_token_transaction')
    op.drop_index(op.f('ix_vbwd_token_transaction_reference_id'), table_name='vbwd_token_transaction')
    op.drop_table('vbwd_token_transaction')
    op.drop_index(op.f('ix_vbwd_tax_rate_tax_id'), table_name='vbwd_tax_rate')
    op.drop_table('vbwd_tax_rate')
    op.drop_table('vbwd_role_permissions')
    op.drop_index(op.f('ix_vbwd_price_currency_id'), table_name='vbwd_price')
    op.drop_table('vbwd_price')
    op.drop_index(op.f('ix_vbwd_payment_method_translation_payment_method_id'), table_name='vbwd_payment_method_translation')
    op.drop_table('vbwd_payment_method_translation')
    op.drop_index(op.f('ix_vbwd_password_reset_token_user_id'), table_name='vbwd_password_reset_token')
    op.drop_index(op.f('ix_vbwd_password_reset_token_token'), table_name='vbwd_password_reset_token')
    op.drop_table('vbwd_password_reset_token')
    op.drop_index(op.f('ix_vbwd_feature_usage_user_id'), table_name='vbwd_feature_usage')
    op.drop_index(op.f('ix_vbwd_feature_usage_period_start'), table_name='vbwd_feature_usage')
    op.drop_index(op.f('ix_vbwd_feature_usage_feature_name'), table_name='vbwd_feature_usage')
    op.drop_table('vbwd_feature_usage')
    op.drop_index(op.f('ix_taro_card_draw_session_id'), table_name='taro_card_draw')
    op.drop_index(op.f('ix_taro_card_draw_position'), table_name='taro_card_draw')
    op.drop_index(op.f('ix_taro_card_draw_arcana_id'), table_name='taro_card_draw')
    op.drop_table('taro_card_draw')
    op.drop_index(op.f('ix_shop_product_variant_sku'), table_name='shop_product_variant')
    op.drop_index(op.f('ix_shop_product_variant_product_id'), table_name='shop_product_variant')
    op.drop_table('shop_product_variant')
    op.drop_index(op.f('ix_shop_product_review_user_id'), table_name='shop_product_review')
    op.drop_index(op.f('ix_shop_product_review_status'), table_name='shop_product_review')
    op.drop_index(op.f('ix_shop_product_review_product_id'), table_name='shop_product_review')
    op.drop_table('shop_product_review')
    op.drop_index(op.f('ix_shop_product_image_product_id'), table_name='shop_product_image')
    op.drop_table('shop_product_image')
    op.drop_table('shop_product_category_link')
    op.drop_index(op.f('ix_shop_abandoned_cart_user_id'), table_name='shop_abandoned_cart')
    op.drop_index(op.f('ix_shop_abandoned_cart_status'), table_name='shop_abandoned_cart')
    op.drop_index(op.f('ix_shop_abandoned_cart_invoice_id'), table_name='shop_abandoned_cart')
    op.drop_table('shop_abandoned_cart')
    op.drop_index(op.f('ix_ghrm_user_github_access_user_id'), table_name='ghrm_user_github_access')
    op.drop_table('ghrm_user_github_access')
    op.drop_index(op.f('ix_coupon_discount_id'), table_name='coupon')
    op.drop_index(op.f('ix_coupon_code'), table_name='coupon')
    op.drop_table('coupon')
    op.drop_index(op.f('ix_cms_page_style_id'), table_name='cms_page')
    op.drop_index(op.f('ix_cms_page_slug'), table_name='cms_page')
    op.drop_index(op.f('ix_cms_page_preview_token'), table_name='cms_page')
    op.drop_index(op.f('ix_cms_page_layout_id'), table_name='cms_page')
    op.drop_index(op.f('ix_cms_page_category_id'), table_name='cms_page')
    op.drop_table('cms_page')
    op.drop_index(op.f('ix_cms_menu_item_widget_id'), table_name='cms_menu_item')
    op.drop_index(op.f('ix_cms_menu_item_parent_id'), table_name='cms_menu_item')
    op.drop_table('cms_menu_item')
    op.drop_index(op.f('ix_cms_layout_widget_widget_id'), table_name='cms_layout_widget')
    op.drop_index(op.f('ix_cms_layout_widget_layout_id'), table_name='cms_layout_widget')
    op.drop_table('cms_layout_widget')
    op.drop_index(op.f('ix_booking_resource_slug'), table_name='booking_resource')
    op.drop_table('booking_resource')
    op.drop_index(op.f('ix_vbwd_user_status'), table_name='vbwd_user')
    op.drop_index(op.f('ix_vbwd_user_payment_customer_id'), table_name='vbwd_user')
    op.drop_index(op.f('ix_vbwd_user_email'), table_name='vbwd_user')
    op.drop_table('vbwd_user')
    op.drop_index(op.f('ix_vbwd_token_bundle_is_active'), table_name='vbwd_token_bundle')
    op.drop_table('vbwd_token_bundle')
    op.drop_index(op.f('ix_vbwd_tax_country_code'), table_name='vbwd_tax')
    op.drop_index(op.f('ix_vbwd_tax_code'), table_name='vbwd_tax')
    op.drop_table('vbwd_tax')
    op.drop_index(op.f('ix_vbwd_tarif_plan_category_slug'), table_name='vbwd_tarif_plan_category')
    op.drop_index(op.f('ix_vbwd_tarif_plan_category_parent_id'), table_name='vbwd_tarif_plan_category')
    op.drop_table('vbwd_tarif_plan_category')
    op.drop_index(op.f('ix_vbwd_role_name'), table_name='vbwd_role')
    op.drop_table('vbwd_role')
    op.drop_index(op.f('ix_vbwd_permission_resource'), table_name='vbwd_permission')
    op.drop_index(op.f('ix_vbwd_permission_name'), table_name='vbwd_permission')
    op.drop_table('vbwd_permission')
    op.drop_index(op.f('ix_vbwd_payment_method_is_active'), table_name='vbwd_payment_method')
    op.drop_index(op.f('ix_vbwd_payment_method_code'), table_name='vbwd_payment_method')
    op.drop_table('vbwd_payment_method')
    op.drop_index(op.f('ix_vbwd_currency_code'), table_name='vbwd_currency')
    op.drop_table('vbwd_currency')
    op.drop_index(op.f('ix_vbwd_country_is_enabled'), table_name='vbwd_country')
    op.drop_index(op.f('ix_vbwd_country_code'), table_name='vbwd_country')
    op.drop_table('vbwd_country')
    op.drop_index(op.f('ix_vbwd_addon_slug'), table_name='vbwd_addon')
    op.drop_index(op.f('ix_vbwd_addon_is_active'), table_name='vbwd_addon')
    op.drop_table('vbwd_addon')
    op.drop_index(op.f('ix_taro_session_user_id'), table_name='taro_session')
    op.drop_index(op.f('ix_taro_session_status'), table_name='taro_session')
    op.drop_index(op.f('ix_taro_session_spread_id'), table_name='taro_session')
    op.drop_index(op.f('ix_taro_session_expires_at'), table_name='taro_session')
    op.drop_table('taro_session')
    op.drop_index(op.f('ix_shop_warehouse_slug'), table_name='shop_warehouse')
    op.drop_table('shop_warehouse')
    op.drop_index(op.f('ix_shop_product_category_slug'), table_name='shop_product_category')
    op.drop_index(op.f('ix_shop_product_category_parent_id'), table_name='shop_product_category')
    op.drop_table('shop_product_category')
    op.drop_index(op.f('ix_shop_product_slug'), table_name='shop_product')
    op.drop_index(op.f('ix_shop_product_sku'), table_name='shop_product')
    op.drop_index(op.f('ix_shop_product_is_active'), table_name='shop_product')
    op.drop_table('shop_product')
    op.drop_index(op.f('ix_email_template_event_type'), table_name='email_template')
    op.drop_table('email_template')
    op.drop_index(op.f('ix_discount_slug'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_cms_widget_slug'), table_name='cms_widget')
    op.drop_table('cms_widget')
    op.drop_index(op.f('ix_cms_style_slug'), table_name='cms_style')
    op.drop_table('cms_style')
    op.drop_table('cms_routing_rules')
    op.drop_index(op.f('ix_cms_layout_slug'), table_name='cms_layout')
    op.drop_table('cms_layout')
    op.drop_index(op.f('ix_cms_image_slug'), table_name='cms_image')
    op.drop_table('cms_image')
    op.drop_index(op.f('ix_cms_category_slug'), table_name='cms_category')
    op.drop_index(op.f('ix_cms_category_parent_id'), table_name='cms_category')
    op.drop_table('cms_category')
    op.drop_index(op.f('ix_booking_resource_category_slug'), table_name='booking_resource_category')
    op.drop_table('booking_resource_category')
    op.drop_index(op.f('ix_booking_export_rule_event_type'), table_name='booking_export_rule')
    op.drop_table('booking_export_rule')
    op.drop_index(op.f('ix_booking_custom_schema_slug'), table_name='booking_custom_schema')
    op.drop_table('booking_custom_schema')
    op.drop_index(op.f('ix_arcana_suit'), table_name='arcana')
    op.drop_index(op.f('ix_arcana_rank'), table_name='arcana')
    op.drop_index(op.f('ix_arcana_number'), table_name='arcana')
    op.drop_index(op.f('ix_arcana_name'), table_name='arcana')
    op.drop_index(op.f('ix_arcana_arcana_type'), table_name='arcana')
    op.drop_table('arcana')
    # ### end Alembic commands ###
